name: appBuild

on:
  # Triggers the workflow on pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  buildApp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
      - uses: android-actions/setup-android@v2

      - name: Run script file
        run: |
          chmod +x ./build.sh
          ./build.sh
        shell: bash