name: appRelease

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  buildAppAndPublishToNexus:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
      - uses: android-actions/setup-android@v2

#      - name: Run script file
#        run: |
#          chmod +x ./publish.sh
#          ./publish.sh
#        shell: bash
#        env:
#          OSS_USERNAME: ${{ secrets.OSS_USERNAME }}
#          OSS_PASSWORD: ${{ secrets.OSS_PASSWORD }}
#          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
#          SIGNING_PASS: ${{ secrets.SIGNING_PASS }}

  releaseApp:
    needs: buildAppAndPublishToNexus
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#        with:
#          ref: feature/configure-cicd

      - name: Retrieve the release version
        run: |
          echo "TAG_NAME=$( (grep -w "version" | cut -d= -f2) <common.properties)" >> $GITHUB_OUTPUT
        id: version

#      - name: debug
#        run: |
#          cat CHANGELOG.md
#        id: debug

#      - name: Retrieve the release body
#        run: |
#          GITHUB_RELEASE_BODY=$(cat CHANGELOG.md | tr '\n' ';;' |  grep -oE "\#{1,2}\ *$TAG_NAME[^\#]*(\#|\Z)" | tr ';;' '\n' | sed '/^#/d' | tr -d '-' | sed 's/ //')
#          echo "::set-output name=content::$GITHUB_RELEASE_BODY"
#        id: gitHubReleaseBody
#        env:
#          TAG_NAME: ${{ steps.version.outputs.TAG_NAME }}

      - name: Retrieve the release body
        run: |
          message=$(cat CHANGELOG.md | tr '\n' ';;' |  grep -oE "\#{1,2}\ *$TAG_NAME[^\#]*(\#|\Z)" | tr ';;' '\n' | sed '/^#/d' | tr -d '-' | sed 's/ //' | tr '\n' ' '')
          echo "GITHUB_RELEASE_BODY=$message" >> $GITHUB_OUTPUT
          printenv
#          echo "GITHUB_RELEASE_BODY=$(cat CHANGELOG.md | tr '\n' ';;' |  grep -oE "\#{1,2}\ *$TAG_NAME[^\#]*(\#|\Z)" | tr ';;' '\n' | sed '/^#/d' | tr -d '-' | sed 's/ //' | sed -e 's/ /_/g')" >> $GITHUB_ENV
        id: gitHubReleaseBody
        env:
          TAG_NAME: ${{ steps.version.outputs.TAG_NAME }}

      - name: debug
        run: |
          printenv | grep GITHUB_RELEASE_BODY
        shell: bash
        id: debug
        env:
          GITHUB_RELEASE_BODY: ${{ steps.gitHubReleaseBody.outputs.GITHUB_RELEASE_BODY }}

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: "v${{ steps.version.outputs.TAG_NAME }}"
          name: "v${{ steps.version.outputs.TAG_NAME }}"
#          body: "${{ steps.gitHubReleaseBody.outputs.GITHUB_RELEASE_BODY }}"
#          bodyFile: "CHANGELOG.md"
          body: "true"